build.zig, src/modules/boards.zig, src/modules/boards/stm32f3discovery/stm32f3discovery.zig, src/modules/chips.zig, src/modules/chips/stm32f30x/registers.zig, src/modules/chips/stm32f30x/stm32f30x.zig, src/modules/cpus.zig, src/modules/cpus/cortex-m4/cortex-m4.zig, tests/blinky.zig
So this is my first humble success in the microzig world: a red blinking led on STM32F3DISCOVERY.
Completely incomplete, of course, but it is _something_. :-)
=> Support STM32F3DISCOVERY board

src/core/microzig.zig, src/core/mmio.zig, src/modules/chips/lpc1768/lpc1768.zig, src/modules/chips/lpc1768/registers.zig
- MMIO now is forced inline
- microzig.panic now employs logging for panic. This allows the user to implement their custom logging via standard utilities
- LPC1768 is up to date
=> Diverse fixes

src/core/gpio.zig, src/modules/chips/stm32f407/stm32f407.zig, tests/uart-sync.zig
Allow using all UARTs on the STM32F407. Meanwhile, introduce Alternate Functions to GPIO.
=> Improve STM32F407 Uart and introduce GPIO Alternate Function

src/main.zig
The idea here is that someone could write an `nrf52` package that makes working with registers more readable. Similar to how the sdk has some nice-to-use functions for setting up gpio. This sort of package would depend on microzig only. 
Wrt to the generalized interfaces we've discussed, I see packages like these having implementations that can fully take advantage of hardware, and can return a generalized structure. This would be analogous to how you could have a `CountingReader`, and a `GzipReader`, but you call `reader()` on them to get a generalized reader.
=> add hal package option

src/core/clock.zig, src/modules/boards/arduino-nano/arduino-nano.zig, src/modules/boards/mbed-lpc1768/mbed-lpc1768.zig, src/modules/boards/stm32f4discovery/stm32f4discovery.zig, src/modules/chips/atmega328p/atmega328p.zig, src/modules/chips/lpc1768/lpc1768.zig, src/modules/chips/stm32f303/stm32f303.zig, src/modules/chips/stm32f407/stm32f407.zig, src/modules/chips/stm32f429/stm32f429.zig
While this does not automate clock configuration yet, at least it allows using
microzig with applications that configure the clock themselves and then declare
the speeds of the various domains.
Without this, all peripheral depending on different clock domanins (e.g. Uart or
I2C on STM32 devices) could only work with the reset frequency.
=> Add support for multiple clock domains

src/core/pin.zig
`board:` and `chip:` can be prefixed to the pin to force using a pin defined in the board or in the chip. Currently though, neither chips or boards are handling this prefix.
Since this is just used to give priority when parsing the pin, this commit removes the namespace from the spec passed to parsePin. This isolates the namespace handling to the Pin type creation, without having to handle it in chips and boards.
=> pin: omit board/chip namespace when parsing and saving the pin name

src/core/uart.zig, src/modules/boards/stm32f3discovery/stm32f3discovery.zig, src/modules/chips/atmega328p/atmega328p.zig, src/modules/chips/lpc1768/lpc1768.zig, src/modules/chips/stm32f303/stm32f303.zig, src/modules/chips/stm32f407/stm32f407.zig, tests/uart-sync.zig
Some microcontrollers allow routing multiple pins to the same UART peripheral.
This commit allows selecting specific pins on these platforms.
=> uart: allow selecting the tx/rx pins

src/modules/chips/stm32f407/stm32f407.zig
USARTs 1 and 6 are clocked by APB2
=> stm32f407: use the correct bus frequency to calculate usartdiv

src/core/i2c.zig, src/modules/chips/stm32f303/stm32f303.zig, src/modules/chips/stm32f407/stm32f407.zig
- Allow configuring the target speed at runtime
- Allow selecting specific pins for scl and sda
- Add I2C support to `stm32f407` chip
=> I2C improvements

src/main.zig
Make the microzig package public.
When creating hal libraries, microzig must be available to the hal.
Having it public permit the following pattern:
`libs/stm32l0x1/lib.zig`
```zig
pub fn Lib(comptime microzig: anytype) type {
return struct {
pub const chips = struct {
pub const stm32l011f3px = microzig.Chip{
.name = "STM32L011F3Px",
.path = root() ++ "src/registers.zig",
.cpu = microzig.cpus.cortex_m0plus,
.memory_regions = &.{
.{ .kind = .flash, .offset = 0x08000000, .length = 8 * 1024 },
.{ .kind = .ram, .offset = 0x20000000, .length = 2 * 1024 },
},
};
pub const stm32l011f4px = microzig.Chip{
.name = "STM32L011F4Px",
.path = root() ++ "src/registers.zig",
.cpu = microzig.cpus.cortex_m0plus,
.memory_regions = &.{
.{ .kind = .flash, .offset = 0x08000000, .length = 16 * 1024 },
.{ .kind …
```
=> Make the microzig package public to allow it to be passed as dependency.

README.adoc
When writing a HAL, having the chip name is very important to switch features and select pinout. Mention the config in the README in a concise manner.
=> Add comment about microzig.config

src/main.zig
Add executable methods (addOptions, addObjectFile) and fix recursive call in addIncludePath.
For #72.
=> Add executable methods and fix recursive call

src/modules/boards.zig, src/modules/boards/stm3240geval/stm3240geval.zig
Same chip as `stm32f4discovery`.
Currently exposes only the 4 LEDs.
Will add more as I continue working with the board.
=> STM3240G-eval board

build.zig, src/modules/boards.zig, src/modules/boards/arduino-uno/arduino-uno.zig, src/modules/chips/atmega328p/atmega328p.zig, tests/blinky.zig, tests/uart-sync.zig
- Added support for Arduino Uno
- Fixed uart specific compile error in atmega328p.zig
=> add arduino uno board

src/core/microzig.zig
Signed-off-by: Connor Rigby <connorr@hey.com>
=> stdlib: allow app to override the zig os layer

src/core/microzig.zig
ziglang/zig#14181 changed the interface for overriding the log function. Previously, you would define a public `root.log` function. Now, you define a `root.std_options` namespace that has a `logFn` decl.
=> Use `root.std_options` to override log behaviour

.github/workflows/build.yml, build.zig, src/main.zig
Catchup to changes introduced by https://github.com/ziglang/zig/pull/14498
=> Catchup to changes introduced by ziglang/zig#14498

build.zig, src/core.zig, src/core/usb.zig, src/core/usb/hid.zig
I've extracted the platform independent code from the rp2040 device impl (see ZigEmbeddedGroup/raspberrypi-rp2040#40).
One can create a concrete implementation by calling `Usb(F)`, where `F` is a struct that contains a set of functions to handle the low level details (register access etc.).
Check out the usb examples in the [rp2040 repo](https://github.com/r4gus/raspberrypi-rp2040/blob/main/examples/usb_hid.zig)!
@MasterQ32 @mattnite
=> Abstract USB device implementation

README.adoc, src/core/experimental/clock.zig, src/core/experimental/debug.zig, src/core/experimental/i2c.zig, src/core/experimental/uart.zig
Mostly changes to imports/variables that changed.
The i2c fix prevents the controller form hanging/crash when running this line
`const i2c = try interfaces.i2c.I2CController(0, .{}).init(.{ .target_speed = 400_000 });`.
I think this is caused because the struct that is returned contains just functions so it has size 0 and clangs avr code gen cant handle that properly.
=> Updated code to regz rewrite and added fix for i2c on ATmega328P

src/core/usb.zig, src/modules/cpus/cortex-m.zig, src/modules/cpus/riscv32.zig, src/start.zig
with PR: [15278](https://github.com/ziglang/zig/pull/15278) merged, zig master now uses @memcpy and @memset builtin instead of mem.copy, mem.set, this MR update all usage of mem.copy and mem.set to use builtins.
=> update to zig master: use @memset, @memcpy builtin

build.zig
With new module architecture, the added option would not be visible in the app module. This fixes that.
For example here is how options works, in `build.zig`
```zig
var buf: [100]u8 = .{0} ** 100;
const date = std.fmt.bufPrint(
&buf,
"{d}",
.{std.time.timestamp()},
) catch unreachable;
const options = b.addOptions();
options.addOption([]const u8, "date", date);
exe.addOptions("compile_info", options);
```
Then in app main file.
```zig
const compile_info = @import("compile_info");
...
debug(compile_info.date, .{});
```
=> When adding an option, set it as app module dependency

src/modules/cpus/avr5.zig
@call built-in function parameter changed from CallOptions in zig 0.10 to CallModifier in zig 0.11.
=> Fix @call parameter for zig 0.11

build.zig
Hi Team Microzig!
I have updated my microzig fork to use the LazyPaths and CSourceFiles used in the v0.11.0 compilation. 
This fixes my personal project  (https://github.com/FranciscoLlobet/efm32-freertos-zig)
Thanks in advance and Best Regards
Francisco
=> Fixing issues in Build to achieve v0.11.0 compatibility

src/core/experimental/debug.zig, src/core/experimental/i2c.zig, src/core/experimental/spi.zig, src/core/experimental/uart.zig
This is to follow the STM32 HAL implementations in stmicro-stm32, which were converted to snake_case() when they were extracted from the main microzig repository into their own separate repository.
=> Change the HAL API to snake_case() from camelCase()

src/core/usb.zig, src/core/usb/hid.zig
This fixes an issue where the descriptors were the wrong size, leading to unexpected behavior and incorrect values in fields.
=> packed struct => extern struct for USB

build.zig
The reason behind this change is that I'm unable to specify a chip, hal, or board definition in a local project and that's a pattern that we explicitly want to handle. This means packages must provide an absolute path to their files, which is already done throughout our small ecosystem.
In the future I'd like to change the API so package creators or those vendoring everything locally give a relative path.
=> Use root build for chips, hals, and boards

tools/bundle.py
Support bundling only specified boards and skipping the examples. This speedsup the process in case
the developer is only working on specific boards
at a time. By default every example and every board are bundled.
=> support bundling only specific boards

README.md
The patch tool expects the build.zig.zon file as
it's argument not the project folder.
=> fix documentation for patch tool

board-support/raspberrypi-rp2040/src/hal/dma.zig
`i` is `usize` but `channel()` expects a `u4`.
=> hal: dma: Cast channel index in claim_unused_channel

README.md, tools/requirements.txt
=> Fix requirements.txt and update README

board-support/raspberrypi-rp2040/src/hal/dma.zig
Fixes #175.
Had to figure out how to get it to compile, had to add the @TypeOf thing. Thanks to the people on the zig discord who helped me out!
=> rp2040: Fix DMA not respecting transfer_size_bytes

board-support/raspberrypi-rp2040/src/hal/pio.zig
This field is a bit tricky: It belongs to the EXECCTRL register, while most of the other fields can determined based on the directives used in the assembled program, this one has to be set explicitly. This makes it so that we have to plumb some way to explicitly set the field. I did this by making `LoadAndStartProgramOptions` take `ExecOptions`, but this isn't perfect, because if a user sets other fields, they will be ignored in favour of the values set in the program.
=> rp2040: Add support for PIO's jmp_pin

board-support/raspberrypi-rp2040/src/hal/usb.zig, build/build.zig, core/src/core/usb.zig, core/src/core/usb/hid.zig, examples/raspberrypi-rp2040/src/usb_device.zig, examples/raspberrypi-rp2040/src/usb_hid.zig
The length parameters in USB packets are strict and the existing implementation does already hardcode the length within the serialize functions. Therefore the user should not provide these lengths during creation time. In order to make this more verbose use defaults values within the structs and reference these defaults values within the serialization functions. It's not possible to remove these fields completly as this fields are used within deserialization from the hardware itself.
=> usb: unify handling of length parameters

board-support/stmicro-stm32/build.zig
Added the STM32F407 hal source file, so that we can build a zig program targeting the F407
=> hal: stm32f407: Added stm32f407 source file to the build configuration

board-support/raspberrypi-rp2040/src/hal/flash.zig, examples/raspberrypi-rp2040/build.zig, examples/raspberrypi-rp2040/src/flash_id.zig
Add a function to read ID from flash in RP2040, which is unique for each chip and can be used as a serial number.
=> rp2040: add flash id function

bsp/raspberrypi/rp2040/src/hal/pins.zig
Was getting the error
```
error: root struct of file 'hal.gpio' has no member named 'set_pull'
gpio.set_pull(gpio_num, pull);
~~~~^~~~~~~~~
```
I don't know if this is the best way to do this, but it seems to work.
=> Fix setting pull direction in pinConfig

tools/regz/src/gen.zig
This padding is necessary for types inside arrays so that the array elements are correctly spaced.
Unblocks [sycl-badge](https://github.com/ZigEmbeddedGroup/sycl-badge)
=> fix regz output for sycl-badge

bsp/espressif/esp/src/cpus/espressif-riscv.zig, build/src/generate_linkerscript.zig
This PR fixes the following issues:
1. Accounts for the possibility of the `.sdata*` sections being generated. These sections are created by compilers in order to optimize access for small data on some architectures. Right now this breaks the `espressif/esp` example the `.sdata` output section is being automatically placed at the wrong place, creating an incorrect and enormous binary.
2. Properly provide the `__global_pointer$` used in the RISC-V architecture CPUs to initialize the GP register. This register is then used in order to improve access times to frequently used data, as long as it is +-2048 bytes away by fitting the offset in the immideate part of the instruction.
3. Disables relaxation when initializing the GP register on `espressif-riscv`
References: …
=> Linking and linker relaxation fixes

core/src/core/usb.zig
This PR adds support for chunked data in the USB driver. This is especially required for configuration sections larger than the endpoint's maximum packet size.
=> USB driver: support chunked data

bsp/gigadevice/gd32/build.zig, bsp/gigadevice/gd32/src/hals/GD32VF103/gpio.zig, bsp/gigadevice/gd32/src/hals/GD32VF103/hal.zig, bsp/gigadevice/gd32/src/hals/GD32VF103/pins.zig, bsp/gigadevice/gd32/src/hals/GD32VF103/uart.zig, examples/gigadevice/gd32/build.zig, examples/gigadevice/gd32/src/blinky.zig
I am new of zig, but I have developed in embedded RTOS.
I would to learn to use the zig language programming, starting from the longan clone gd32f103 board, that have on hand. 
In this pull request I start to implement the gpio driver take example from the stmicro support.
I do the blinky example and works, but I would ask you if I am correct and the code architecture could be good.
Now I am continuing with the uart.
Let me know what do think.
=> Complete Gd32f103 Support

core/src/start.zig
Before, Zig didn't find my app provided panic handler.
Also, manages to avoid the use of `usingnamespace`.
=> Use app provided panic handler if it exists

bsp/raspberrypi/rp2040/src/hal/i2c.zig
A call to `i2c.disable()` was immediately followed by an inlined copy of its body. I2C is still working for me with this change.
=> rp2040: remove redendant code in I2C.apply()

bsp/raspberrypi/rp2040/src/hal/hw.zig, bsp/raspberrypi/rp2040/src/hal/resets.zig
And also remove couple of redundant `@as` usages.
Partially fixes #214
=> fix(rp2040) apply broken codegen workaround to both busy loop

core/src/mmio.zig, tools/regz/src/mmio.zig
In zig 0.11.0, struct field `default_value` always returns an opaque pointer which can't be used in `@tagName`.
I'm not entirely sure how the original API worked but this implementation allows selective toggling of bits in each field of registers via a xor mask:
```
REG.toggle(.{ .FIELD = MASK });
```
=> Fix mmio toggle

build/build.zig
- Add `strip_unused_symbols` field to `FirmwareOptions` so that by default, unused symbols are stripped at link time from binaries in all optimization modes
=> Strip Unused Symbols at Link Time

bsp/raspberrypi/rp2040/src/hal.zig, bsp/raspberrypi/rp2040/src/hal/adc.zig, bsp/raspberrypi/rp2040/src/hal/gpio.zig, bsp/raspberrypi/rp2040/src/hal/i2c.zig, bsp/raspberrypi/rp2040/src/hal/pins.zig, examples/raspberrypi/rp2040/src/i2c_bus_scan.zig
There's enough changes here that I felt it deserved a mini writeup. There was a couple of opinionated decisions I made as well to the API that I wanted to call out and get others opinions on.
- Various performance improvements to I2C reads/writes related to how/when polling occurs
- Simplified API so that all reading/writing happens in 3 functions
- Tweaked how I2C is "initialized" and "deinitialized"
- Corrected how baud rate is translated to register settings for I2C timing
- Moved most of the error handling responsibility onto the caller of the I2C API, for example code no longer calls `panic()`, but rather bubbles up an error to the caller for them to make a decision on
- Added "const correctness" to API
- Added comments being explicit about what features of the hardware this API …
=> RP2040 I2C Refactor

bsp/espressif/esp/src/example/blinky.zig, bsp/espressif/esp/src/hals/ESP32_C3.zig, bsp/espressif/esp/src/hals/esp32-c3/gpio.zig, bsp/espressif/esp/src/hals/esp32-c3/uart.zig, examples/espressif/esp/src/blinky.zig
This adds a first iteration of the `ESP32-C3` (later to be universal) GPIO HAL driver, and factors it out into its own file.
=> Initial ESP32-C3 GPIO HAL driver

bsp/raspberrypi/rp2040/src/hal.zig, bsp/raspberrypi/rp2040/src/hal/uart.zig, examples/raspberrypi/rp2040/src/adc.zig, examples/raspberrypi/rp2040/src/flash_id.zig, examples/raspberrypi/rp2040/src/flash_program.zig, examples/raspberrypi/rp2040/src/i2c_bus_scan.zig, examples/raspberrypi/rp2040/src/random.zig, examples/raspberrypi/rp2040/src/uart.zig, examples/raspberrypi/rp2040/src/usb_cdc.zig, examples/raspberrypi/rp2040/src/usb_hid.zig
Should start looking pretty familiar to the other PRs!
The highlights:
- Removed configuration of GPIO pins by driver
- Added full transaction error handling
- Consolidated to new "uart.instance.[]" design pattern
- Added new "apply()" and "apply_runtime()" pattern for dual comptime/runtime error checking
- Added querying of current active UART errors
- Tweaked + renamed to write_blocking() and read_blocking() and added a timeout to match other APIs
- Tweaked syntax for using the UART as a logger + added ability to remove uart as logger
=> RP2040 Uart Refactor

examples/raspberrypi/rp2040/src/gpio_clk.zig
Was testing the clock and couldn’t get it working because the global config never gets applied as is.
=> Fix rp2040 gpio_clock example.

examples/espressif/esp/src/blinky.zig
I was looking through the example for esp 32 for micro zig and I noticed a small bug/typo in setting blue led to high.
=> ESP 32 blinky example - typo fix

port/raspberrypi/rp2xxx/src/hal/pins.zig
Just got around to updating microzig to past @haydenridd's SPI and I2C re-writes. Formerly, the function and pull were set by the I2C interface.
=> https://github.com/ZigEmbeddedGroup/microzig/pull/213/files#diff-8a4efe08a401e079bae57d66c0dd3ef49a3839a6065c3c1058ac8a0eaf142623L110
Since that's no longer the case, I'd like to set the function in the pins interface. This Microzig patch lets me do that.
=> https://tildegit.org/matthias/Micromouse/src/branch/master/src/physical-bot.zig#L212
Arguably we could/should also set the direction and pull based off of these properties (previously the I2C interface used `set_pull(.up)` on both pins), but it's slightly less obvious how to do that correctly and doesn't seem to be necessary in my test.
=> Support I2C and SPI functions in the pins abstraction

build.zig, core/build.zig, port/stmicro/stm32/src/chips.zig, port/stmicro/stm32/src/generate.zig
This PR adds some logic to use the floating point version of a target if the core has an interrupt labeled "FPU". It also adds a target with the FPU features set and hard float abi for the M33 and M7 cores, and for the non-f M7 it sets the soft float abi.
Also makes the register defs path public in chips.zig so a user can specify their own target but still use the generated registers if they need to for whatever reason.
Addresses https://github.com/ZigEmbeddedGroup/microzig/issues/245#issue-2568813840
=> Generated STM32 targets with FPU

port/raspberrypi/rp2xxx/src/hal/usb.zig
Before the rework on resets.zig the mask had all of the rp2xxx hal/resets.zig Mask had all of the values in the packed struct as false by default, so when reset.reset(.{pll_usb}) was run, it would make a bitmask for only that register. But now it makes a bitmask for every register and takes all pins out of reset mode.
I just made it so it gets the bit offset of the register and creates a bitmask for only the register in question. This should support rp2040 and rp2350, but currently is only tested with the usb cdc example on the rp2040.
=> Fixed RP2xxx usb reset register masks

core/src/cpus/cortex_m/m33.zig
Provides a minimal implementation of `core/src/cpus/cortex_m/m33.zig` derived from the [official documentation](https://www.st.com/resource/en/programming_manual/pm0264-stm32-cortexm33-mcus-programming-manual-stmicroelectronics.pdf).
=> Register Map Implementation for Cortex M33

core/src/cpus/cortex_m.zig, core/src/cpus/cortex_m/m0plus.zig
Hi! Am working on a hobby project with a stm32g030, and have just been trying to get interrupts working. Turns out I needed NVIC registers. This change adds the NVIC registers. I wrote it by hand; if it can be generated, that'd avoid any of my math mistakes!
=> adding NVIC registers for cortex m0+, fixing little bug with stringToEnum

core/src/core/usb.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/usb_cdc.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/usb_hid.zig, port/raspberrypi/rp2xxx/src/hal/usb.zig
Previous USB refactor for simplification assumed a fixed number of 4 USB endpoints. This PR introduces a configuration option to specify the desired number of endpoints, but no more than the board's maximum number of endpoints. Every board have to provide its own config with proper defaults which coresponds to max number of supported endpoints.
=> Comptime USB endpoints number

build.zig, examples/build.zig, examples/gigadevice/gd32/build.zig, examples/microchip/atsam/build.zig, examples/microchip/avr/build.zig, examples/nordic/nrf5x/build.zig, examples/nxp/lpc/build.zig, examples/raspberrypi/rp2xxx/build.zig, examples/stmicro/stm32/build.zig, tools/package-test/build.zig, tools/package-test/build.zig.zon
* Fixed `MicroBuild.init` just exiting the build process without fetching any ports when using the packaged version of microzig. Now it returns an optional. In case some port dependencies haven't been fetched yet, it returns null.
* Update all examples.
* Update and fix `package-test`.
* Fix other compilation errors.
* Example usage of `MicroBuild` in a comment.
=> Build system bug fix

build.zig, core/src/cpus/cortex_m.zig, core/src/cpus/cortex_m/m0.zig, core/src/cpus/cortex_m/m0plus.zig, core/src/cpus/cortex_m/m3.zig, core/src/cpus/cortex_m/m33.zig, core/src/cpus/cortex_m/m4.zig
* I added `NVIC`, `SCB`, `SysTick` and `MPU` to all cortex-m cpus.
** There are some comments missing in cortex-m3 and cortex-m4 in some registers.
** In cortex-m33 some registers are still u32. The same for some in cortex-m3 and cortex-m4.
* Minimal refactoring in build.zig.
=> cortex_m: Add core peripherals

core/src/cpus/cortex_m.zig, core/src/cpus/cortex_m/m7.zig, core/src/cpus/cortex_m/m7_utils.zig
This PR adds some basic cortex-m7 register definitions.
I verified that ITM, TPIU, and DBG work on an STM32f746ng-disco board with this sample code to write debug info through SWD:
```zig
const std = @import("std");
const microzig = @import("microzig");
const stm32 = microzig.hal;
const cpu = microzig.cpu;
pub fn initSWO() void {
// Enable trace in core debug:
cpu.dbg.DEMCR.modify(.{ .TRCENA = 1 }); // Enable debugging & monitoring
// Enable ITM:
cpu.itm.TCR.modify(.{
.ITMENA = 1, // Enable ITM
.SYNCENA = 1, // Enabe sync packets
.TXENA = 1, // Enable DWT packets
.TraceBusID = 1, // Unique ID for multi-source trace
});
// Enable stimulus port 0:
cpu.itm.TER[0].modify(.{ .STIMENA = 1 });
// Configure Serial Wire Output (SWO):
cpu.tpiu.SPPR.modify(.{ .TXMODE = 0b10 }); // NZ mode …
```
=> Add cortex m7 register definitions

port/raspberrypi/rp2xxx/src/hal/pio.zig
This is needed, for example, to wait on an interrupt from a Pio program.
See https://github.com/Grazfather/microzig/commit/9fba01b5ae818607d4b6ae85b0bbb04840ddba43.
I would be open to adding some method to actually just wait on an interrupt, but not sure what you might want that interface to look like.
=> rp2xxx: Make pio.Irq.get_irq_regs public

core/src/core/usb/cdc.zig, core/src/cpus/cortex_m.zig, core/src/cpus/cortex_m/m0.zig, core/src/cpus/cortex_m/m0plus.zig, core/src/cpus/cortex_m/m3.zig, core/src/cpus/cortex_m/m33.zig, core/src/cpus/cortex_m/m4.zig, core/src/cpus/cortex_m/m7.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/usb_cdc.zig
- replace wrong cortex m0 plus cpu name
- don't set reserved fields by default to 0
- remove underscores of reserved bits (to look more similar to what `regz` generates)
=> core: Fix wrong cpu name for cortex m0 plus

build.zig
- Fix bug in `add_firmware` where `options.hal` or `options.board` are not actually overriding the `Target`.
=> build-system: Fix bug in `add_firmware`

core/src/core/usb.zig, port/raspberrypi/rp2xxx/src/hal/usb.zig
This PR refactors RP2xxx USB driver:
- Code reduction by removing branching per endpoint number 
- Improved endpoint data buffer allocation
- Some name changes to align interface more with TinyUSB project
=> [RP2xxx] USB driver refactory work

examples/raspberrypi/rp2xxx/src/blinky.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/pwm.zig, port/raspberrypi/rp2xxx/src/hal/pins.zig, port/raspberrypi/rp2xxx/src/hal/pwm.zig
**TL;DR:** Replaces `pins = pin_config.apply()` with `pins = comptime pin_config.pins(); pin_config.apply()`.
**Long version:**
This PR updates the "pin configuration helper," `pins.GlobalConfiguration`, to return a `pins` type which is more suitable for normal usage than the ad-hoc zero-sized-types previously created. For example, a `pins.led_a` could be saved into a runtime struct or passed to a struct initializer at comptime, just like a primitive Zig value. In order to make this possible, there are a couple of distinct changes being made:
1. For .sio-function pins, the resulting pin is now a `gpio.Pin`. This removes the previous ZSTs and unifies the API. As well as making these data that can be used at runtime.
2. For pwm-function pins, the Pwm type has been rewritten to be a …
=> [RP2xxx] Update pins helper to create pins as comptime-available data instead of zero-sized-types

build.zig
Added the ability to run `zig build release-regz` and `zig build release-uf2` which will generate the platform binaries for the respective tools.
This is planned to be used in some CI improvement where regz and uf2 will also be published.
=> Add regz/uf2 release build option

examples/raspberrypi/rp2xxx/README.md, examples/raspberrypi/rp2xxx/build.zig, examples/raspberrypi/rp2xxx/src/watchdog_timer.zig, port/raspberrypi/rp2xxx/README.md, port/raspberrypi/rp2xxx/src/hal.zig, port/raspberrypi/rp2xxx/src/hal/watchdog.zig
Tested on both RP2040 and RP2350! Only functionality I left out was the ability via the scratch registers to force the Pico to boot with a manually specified PC/SP. Wouldn't be that hard to implement, I just don't think there's any demand for it yet since that's a super advanced use case.
=> Added watchdog timer API for both RP2040 and RP2350

examples/raspberrypi/rp2xxx/src/rp2040_only/usb_cdc.zig
This PR removes glitches in the USB CDC example. After sending each data chunk, we must call the main USB task function to ensure bus events are correctly dispatched. 
Additionally, this PR fixes an issue where short data packets were not sent immediately.
I also removed old TODO comment that I forgot to remove in last PR.
=> Fix USB CDC stability issue when sending data

port/raspberrypi/rp2xxx/src/hal/pio/assembler.zig
If the tokenizer index is at the newline at the end of a line and it initializes the diagnostics, the column calculation will underflow, since the line iterator index will point to the end of the next line, while the index will be the previous new line character, so the column will be calculated as -1.
This change simply allows the index to point to the newline, though in this case the diagnostic will point past the end of the line:
```zig
❯ zig build test --summary all
test
└─ run test
└─ zig test Debug native 1 errors
src/hal/pio/assembler.zig:133:13: error: failed to assemble PIO code:
mov osr, rxfifoy
^
hello 155
@compileError(format_compile_error(d.message.slice(), source, d.index));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ …
```
=> pio: Assembler: fix issue in diag when tokenizer has index on newline

port/raspberrypi/rp2xxx/src/hal/pio/assembler.zig
If we ever hit an error case that didn't set diags, we'd error out incorrectly since `compileError` expects a string, not an error.
=> Fix error handling in rp2xxx pio assembler

.github/workflows/ci.yml
I added job dependencies to the ports unit tests job and the examples build job. Neither of these two make sense to run if the overall build failed.
=> Update CI workflow with job dependencies

.github/workflows/deploy.yml
regz and uf2 will now be added as artifacts to github releases
Edit: Tested and working on fork
~~Edit 2: Also currently has the change that renamed boxzer-out.tar.gz to microzig-packaged.tar.gz~~
=> Add regz and uf2 releases to the github deploy action

core/src/cpus/cortex_m/m0plus.zig
Pretty simple one! The bits didn't add up to 32, and I was getting this error:
```
1:34: error: backing integer type 'u32' has bit size 32 but the struct fields have a total bit size of 22
SCR: mmio.Mmio(packed struct(u32) {
```
=> fixing register so there is 32 bits

port/raspberrypi/rp2xxx/build.zig
currently compiling microzig with zig from the fedora repos for the rp2xxx results in an error because the bootrom is larger than expected
this is caused by a patch I added that makes `build-id` default to `.sha1` instead `.none` and unfortunately that also affects the bootrom, this PR explicitly sets it to `.none` again
=> explicitly disable build-id for rp2xxx bootrom

port/stmicro/stm32/src/generate.zig
Attempted to support "extends" syntax in register json files.
The added functions aggregate the extends and injects them into the Json.Value parsed from the register files.
it works by traveling down the "extends" and bringing a dictionary with it adding new "items" or "fields" as it travels down the ancestor's lineage.
I expect I'll have to clean up some stuff. but I was just glad I could get it to work.
It does use a arena allocator for the json injections. so they can be cleaned up at the same time.
=> support "extends" from embassy data.

drivers/framework.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/i2c_bus_scan.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/uart_echo.zig, port/raspberrypi/rp2xxx/src/hal/drivers.zig, port/raspberrypi/rp2xxx/src/hal/i2c.zig, port/raspberrypi/rp2xxx/src/hal/time.zig, port/raspberrypi/rp2xxx/src/hal/uart.zig
Pulled this out from #359
* `Absolute`, `Duration`, and `Deadline` into `framework.time` (not clock since it deals with time)
* rewrite `rp2xxx.hal.time` in terms of those types
=> Move time types (Absolute, Duration, Deadline) from rp2xxx HAL into mdf

port/raspberrypi/rp2xxx/src/hal/gpio.zig
Discovered when moving my example in #359 out of the rp2400-only examples.
This must have been fixed recently.
=> rp2xxx: hal: gpio: Fix rp2350 GPIO reg access

port/raspberrypi/rp2xxx/rp2040.ld, port/raspberrypi/rp2xxx/rp2350_arm.ld, port/raspberrypi/rp2xxx/rp2350_riscv.ld, tools/generate_linker_script.zig
Linker script already exports microzig_flash_start but there was no microzig_flash_end. Both values are useful to caluclate avaliable flash size after program flash.
=> Add microzig_flash_end to linker script

build.zig, tools/generate_linker_script.zig
For ARM-based embedded firmware this requires
explicit declaration of `ARM.extab` sections in linker.d, otherwise the exception tables can incorrectly end up in RAM. (See https://github.com/ziglang/zig/issues/22685.)
(The `.unwind_tables = true` line must be removed for Zig 0.14, which already has this enabled for basically all platforms.)
Implements part of #370 already on Zig 0.13.0.
=> Enable 'unwind_tables' for all platforms (for #370)

port/stmicro/stm32/build.zig, port/stmicro/stm32/src/hals/STM32F303.zig, port/stmicro/stm32/src/hals/STM32F303/gpio.zig, port/stmicro/stm32/src/hals/STM32F303/pins.zig
Based on some initial HAL code that was inspired by the current STM32F103 code, but with some variations that seemed to give a slightly simpler result.
(Also made the old unused HAL code in STM32F303.zig compile, and marked it as 'to be moved to separate files'.)
**NOTE** that this actually requires #371 to be merged first.
=> STM32F303: First HAL fragments (depends on #371)

examples/stmicro/stm32/build.zig, examples/stmicro/stm32/src/blinky.zig
This enables the STM32F3DISCOVERY build of blinky, which blinks all 8 LEDs simulateously.
=> STM32F3DISCOVERY: Working blinky

port/raspberrypi/rp2xxx/src/hal/spi.zig
It's already called by a bunch of inline functions, and there's good reason to expose it directly to clients.
=> rp2xxx: hal: spi: Inline & pub-ify get_regs

examples/raspberrypi/rp2xxx/build.zig
The pico/pico2 part is added automatically for the chip-agnostic examples.
As it is, the files look like `pico2_pico_stepper.elf`
=> rp2xxx: examples: Fix name of 'generic' examples

port/raspberrypi/rp2xxx/src/hal/pins.zig
Pin 11 can not be used for UART0_TX, but pin 12 can.
=> Fix rp2xxx UART0_TX available pins

drivers/stepper/stepper.zig
* Implement `stop`: Sets state machine to immediately stop sending pulses
* Implement `start_brake`: Sets state machine to stop accelerating or stop after `steps_to_brake`
* Expose `motor_steps` in `Stepper_Options`: Allow working with stepper motors that don't have 200 steps per rotation.
=> drivers: stepper: Implement start_brake, stop, & expose motor_steps

port/raspberrypi/rp2xxx/rp2040.ld, port/raspberrypi/rp2xxx/rp2350_arm.ld, port/raspberrypi/rp2xxx/src/bootroms/RP2040/shared/stage2.ld
If building a target after #373 happened to create an `.ARM.extab*` section, it would be placed before `.text`, which would shift the vector table over and prevent the device from booting.
This would happen almost always in debug builds, but could occasionally happen on `--release=fast` builds as well.
Fix this by explicitly placing it after `.text`.
Should fix #373
=> rp2040: Fix extab section getting put before .text

website/content/index.smd
I clicked the SYCL Badge link expecting to see the badge info, but got the landing page instead.
So here's the link to the SYCL Badge. :)
=> doc: add link to SYCL Badge

examples/microchip/avr/build.zig, examples/microchip/avr/src/blinky.zig, port/microchip/avr/src/hals/ATmega328P.zig, port/microchip/avr/src/hals/ATmega32U4.zig
This PR updates the avr example to use `core.experimental`.
In order for the code to compile and run, it needed minor adjustments.
=> avr: update example to use core.experimental

tools/regz/src/Database.zig, tools/regz/src/atdf.zig
Fixes #402
If an enum is not found, `get_enum_by_name` will lookup among the parents of the given struct_id.
On any failure, the original error will be returned.
=> regz: generate enums attached to parent

build.zig, port/raspberrypi/rp2xxx/rp2350_riscv.ld
* add unwind tables option to the build system (fixes #388)
* fix bug where a riscv rp2350 uf2 couldn't be flashed to the pico 2
=> Unwind tables option

port/raspberrypi/rp2xxx/src/hal/pio/assembler/comparison_tests.zig, port/raspberrypi/rp2xxx/src/hal/pio/assembler/encoder.zig
Check that the number of bits required for the delay can fit in the bits leftover after sideset takes its own
=> rp2xxx: pio: Check for sideset/delay collisions

core/src/cpus/cortex_m.zig, core/src/interrupt.zig, core/src/utilities.zig, examples/raspberrypi/rp2xxx/src/interrupts.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/rtc.zig, port/raspberrypi/rp2xxx/src/cpus/hazard3.zig
- (Re)Add support for multiple interrupt calling conventions on cortex_m and hazard3
- use `riscv_interrupt` calling conventions for core interrupts on hazard3 and keep the c calling convention for external interrupts
=> (Re)Add support for multiple interrupt calling conventions

examples/espressif/esp/build.zig, examples/espressif/esp/src/blinky.zig, examples/gigadevice/gd32/build.zig, examples/microchip/atsam/build.zig, examples/microchip/avr/build.zig, examples/no_hal/stm32_l031/build.zig, examples/nordic/nrf5x/build.zig, examples/nxp/lpc/build.zig, examples/raspberrypi/rp2xxx/build.zig, examples/stmicro/stm32/build.zig, examples/wch/ch32v/build.zig
Add an option to all example directories to allow a user to only build examples that only match by name.
So someone could do:
`zig build -Dexample riscv` to build only the riscv versions of rp2xxxx.
Or they could do `zig build -Dexample blinky` to build blinky (for all supported targets)
=> examples: Add 'example' option to only build matches

core/src/core/usb.zig, port/raspberrypi/rp2xxx/src/hal/usb.zig
Previously, the alias was spelled differently from the canonical name.
=> Fix typo in utf8ToUtf16Le alias

core/src/mmio.zig
On MacOS with Zig version 0.14.0, trying to build:
```
const std = @import("std");
const microzig = @import("microzig");
const PPB = microzig.chip.peripherals.PPB;
pub fn main() void {
PPB.NVIC_ISER0.write(.{ .SETENA = 0 });
}
```
With build.zig:
```
const std = @import("std");
const microzig = @import("microzig");
const MicroBuild = microzig.MicroBuild(.{
.rp2xxx = true,
});
pub fn build(b: *std.Build) void {
const mz_dep = b.dependency("microzig", .{});
const mb = MicroBuild.init(b, mz_dep) orelse return;
const firmware = mb.add_firmware(.{
.name = "microzig-test",
.target = mb.ports.rp2xxx.boards.raspberrypi.pico2_arm,
.optimize = .ReleaseSmall,
.root_source_file = b.path("src/main.zig"),
});
mb.install_firmware(firmware, .{});
mb.install_firmware(firmware, .{ .format = .elf });
}
``` …
=> Need more branch quota in Mmio

port/raspberrypi/rp2xxx/src/hal/i2c_slave.zig
I discovered a race condition with a write-restart-read operation where the ISR could be called with both the RESTART and READ_REQ flags set.  
The original code handled the READ_REQ and asked for the read data before handling the RESTART which sent the write data to the user.
Reordering handling of the flags resolves this.
=> Fixed race condition in RP2xxx i2c_slave

port/raspberrypi/rp2xxx/src/hal/adc.zig
This fixes a typo in the use of the FIFO Status and Control register (FSC where it should be FCS)
=> Fix ADC FIFO control and status register name typo

port/raspberrypi/rp2xxx/src/hal.zig
Calling the `rp2xxx.get_cpu_id()` function generates an error: `error: cannot dereference non-pointer type 'mmio.Mmio(chip.types.peripherals.SIO__struct_3160)'`
This change fixes that.
=> Fix RP2xxx get_cpu_id call

examples/raspberrypi/rp2xxx/src/rp2040_only/tiles.zig, examples/raspberrypi/rp2xxx/src/ws2812.zig, tools/regz/src/gen.zig
Would it be worthwhile defaulting padding and reserved bits to zero so we don't have to add a  `.padding = 0,` and the like every time we write to a register?
=> regz: Give default values to padding and reserved bits fields

.github/workflows/ci.yml, .github/workflows/publish-github-pages.yml
In the PR workflow we build the website, but we use zig master. Seems that zig master changed underneath us to make it no longer compatible with the version of zine we pin.
Simply use the 0.14.0 release of zig for this workflow.
=> Fix PR website building gh action

examples/raspberrypi/rp2xxx/src/adc.zig, examples/raspberrypi/rp2xxx/src/changing_system_clocks.zig, examples/raspberrypi/rp2xxx/src/custom_clock_config.zig, examples/raspberrypi/rp2xxx/src/gpio_clock_output.zig, examples/raspberrypi/rp2xxx/src/i2c_bus_scan.zig, examples/raspberrypi/rp2xxx/src/interrupts.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/flash_id.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/flash_program.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/i2c_slave.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/pcf8574.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/random.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/tiles.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/usb_hid.zig, examples/raspberrypi/rp2xxx/src/spi_slave.zig, examples/raspberrypi/rp2xxx/src/squarewave.zig, examples/raspberrypi/rp2xxx/src/stepper.zig, examples/raspberrypi/rp2xxx/src/uart_log.zig, examples/raspberrypi/rp2xxx/src/usb_cdc.zig, examples/raspberrypi/rp2xxx/src/ws2812.zig, port/raspberrypi/rp2xxx/src/hal/i2c.zig
Simply cleanup the examples so that they are more consistent:
1. Remove unused imports
2. Make the uart setup the same across all examples (except where rx is actually needed)
3. Cleanup the pin setup in the stepper example.
Only the stepper example is worth taking a close look at.
=> examples: rp2xxx: Make examples more consistent

port/raspberrypi/rp2xxx/src/hal/usb.zig
In commit 68b5ad1 `rom.memcpy` was replaced by `@memcpy` by @patryk4815  but one more `rom.memcpy` left.
=> RP2XXX USB - replace rom.memcpy with @memcpy

core/src/core/usb.zig, core/src/core/usb/hid.zig, core/src/core/usb/types.zig
This PR includes enough changes to facilitate a working USB HID keyboard implementation using MicroZig.
- Fix critical typo from #426
- Make fields pub that are required for app code to define its own report descriptors
- ACK requests that are required for keyboard; some of these are stubs which need further improvements
I used this code, along with my own application code, to create a USB HID keyboard that connects and types successfully. Tested on macOS Sequoia and Arch Linux. I tried both the included `ReportDescriptorKeyboard` and a custom report format, both work well.
I have done my best to document the areas that were added as stubs and which need improvement.
=> HID: basic keyboard support

drivers/stepper/stepper.zig, examples/raspberrypi/rp2xxx/src/stepper.zig
* Use an absolute time for next action instead of a duration to simplify calculations
* Wait min low time for pulse
* Fix `set_rpm` not working because it didn't have a pointer receiver.
* Make `next_action` return a boolean and just loop on that value in `move`
Fixes #458
=> Fixup stepper

examples/espressif/esp/src/blinky.zig, examples/espressif/esp/src/stepper_driver.zig, port/espressif/esp/src/hal/gpio.zig
* Convert esp `Pin` from a struct to an enum (to match rp2xxx)
* Add `num` function to grab pin (also to match rp2xxx)
=> esp: gpio: Convert pin to enum

core/src/cpus/cortex_m.zig
My earlier testing missed that the ram_vectors array might not have been properly aligned.  This fixes that.
=> Make sure ram_vectors are properly aligned.

drivers/display/common.zig, drivers/display/sh1106.zig, drivers/display/ssd1306.zig, drivers/framework.zig
This adds support for the SH1106 OLED display driver. Tested and working on hardware (SPI only).
This device is very similar to the already supported SSD1306. They are so close that another approach is to create some abstraction over both, but I felt that duplicating code was a cheaper abstraction to start off. Be aware that some of the code and comments are in fact copied directly from the SSD1306 implementation.
Main differences between SH1106 and SSD1306:
- SH1106 only has page addressing mode, no "horizontal" or "vertical" mode.
- Some command values are different, though most of the commands are the same.
Excluded:
- Tests. Should these be included? Are unit tests valuable for these drivers (as opposed to e.g. end-to-end tests on hardware)?
- Framebuffer; would be 100% same as …
=> Add SH1106 driver

drivers/display/ssd1306.zig
With this it can be used as:
```
const  display = try ssd1306.init(.i2c, i2c_device, null);
```
=> [drivers] More user friendly SSD1306 init function

port/raspberrypi/rp2xxx/src/hal/multicore.zig
Correctly pass VTOR to core1 to allow interrupts on both cores.
=> Pass vtor to core1 rp2xxx

tools/regz/src/gen.zig
Add a docstring comment under the register name
```zig
/// I2C (Inter-Integrated Circuit) Controller
pub const I2C0 = extern struct {
/// I2C_SCL_LOW_PERIOD_REG
/// offset: 0x00
SCL_LOW_PERIOD: mmio.Mmio(packed struct(u32) {
/// reg_scl_low_period
SCL_LOW_PERIOD: u9,
padding: u23 = 0,
}),
/// I2C_CTR_REG
/// offset: 0x04
CTR: mmio.Mmio(packed struct(u32) {
/// reg_sda_force_out
SDA_FORCE_OUT: u1,
...
/// offset: 0xe0
reserved240: [16]u8,
```
=> Regz offset comments

port/espressif/esp/src/hal/gpio.zig
1. Fix up `DriveStrength` - The bit values depends on the GPIO number, which is crazy. See page 187 of the TRM
2. Split up setting pulldowns/pullups based on sleep mode (This was previously incorrect).
3. Fix `set_open_drain_output`, which never would have compiled.
=> esp: hal: gpio: Add various fixes and features

drivers/display/sh1106.zig, examples/espressif/esp/build.zig, examples/espressif/esp/src/i2c_bus_scan.zig, examples/espressif/esp/src/i2c_display_sh1106.zig, examples/espressif/esp/src/i2c_temp.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/hd44780.zig, port/espressif/esp/src/hal/drivers.zig, port/espressif/esp/src/hal/i2c.zig
This PR extends the functionality of the hal to support writes larger than the fifo (32 bytes).
It also implements an i2c `Datagram_Device`
Finally, it adds a few examples.
This converts the hal into almost a direct port of [esp-rs](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/src/i2c/lp_i2c.rs)'s I2C HAL
=> esp: hal: i2c (part 2)

port/wch/ch32v/src/cpus/qingkev2-rv32ec.zig, port/wch/ch32v/src/cpus/qingkev3-rv32imac.zig, port/wch/ch32v/src/cpus/qingkev4-rv32imac.zig
Added clock reset to default values after reset, as done in the original HAL from WCH.
This is necessary because different chip revisions may have different default settings. For example, on my 003 chips, the default HB bus frequency is 8 MHz, while it should be 24 MHz. This code fixes that.
Tested on: CH32V003 and CH32V305
=> WCH CH32V: add system clock init

examples/wch/ch32v/src/blinky.zig, examples/wch/ch32v/src/blinky_ch32v003.zig, examples/wch/ch32v/src/board_blinky.zig
=> WCH CH32V: examples: replace busyloop with busy_delay

port/wch/ch32v/src/cpus/qingkev2-rv32ec.zig, port/wch/ch32v/src/cpus/qingkev3-rv32imac.zig, port/wch/ch32v/src/cpus/qingkev4-rv32imac.zig
~Depends on: https://github.com/ZigEmbeddedGroup/microzig/pull/520
Please review only this commit: https://github.com/ZigEmbeddedGroup/microzig/pull/522/commits/2281a878cbf53fc56c45bfe414eccc0bf462e5d4~
Because `_start` is called during an interrupt, calling external functions causes the microcontroller to hang.
This is not noticeable during debugging, since everything works after flashing, but if the microcontroller is powered off, it won't start on the next power-up, not even after pressing the reset button.
This doesn't affect the `ch32v003`, as it has no reset interrupt, but I decided to make everything consistent.
Tested on: CH32V003 and CH32V305
=> WCH CH32V: fix cpu startup

sim/aviron/src/main.zig
This should fix #524.
Use the physical address from the header, rather than the virtual. This makes it so that `.data` (which has a 'physical' on flash and a 'virtual' in sram) is copied to flash and counts on the copying stub to copy it into memory.
This will break any elf (or test elf) that counts on aviron doing the lifting here.
=> Aviron: Fix ELF loading

port/raspberrypi/rp2xxx/src/hal/multicore.zig
When starting core1 when running riscv the vector table needs to be read from mtvec.  The VTOR register arm cores use is not available.
=> Read vector from mtvec not vtor when starting core 1 on riscv core.

port/raspberrypi/rp2xxx/build.zig, port/raspberrypi/rp2xxx/src/boards/adafruit_metro_rp2350.zig, port/raspberrypi/rp2xxx/src/hal/adc.zig, port/raspberrypi/rp2xxx/src/hal/compatibility.zig, port/raspberrypi/rp2xxx/src/hal/gpio.zig, port/raspberrypi/rp2xxx/src/hal/pins.zig
Addresses #405, #311 
Supersedes PR #531.
Improves support for RP2350, especially the RP2350B.  Some of the changes:
- Adds support for GPIO pins 30 through 47.
- Adds support for extra ADC pins and the change in location of the ADCs (pin 40-47 vs 26-30)
- Adds basic support for external PSRAM (R/W memory located at 0x1100_0000)
- Adds UART alternate RX an TX pins (also for RP2350A)
- Adds support in `pins.zig` for PI02. (it looks like `pio.zig` already has needed changes) 
- Adds support in `pins.zig` for PWM8 through PWM11 (changes to `pwm.zig` may be needed)
- Adds support for the Adafruit Meto RP2350 board (that uses the RP2350B chip).
Some things that the RP2350 supports that are not (yet) addressed:
- HSTX support (pin type is set in `pins.zig`)
- TRNG support
- Always-On Timer …
=> Rp2350 support improvement

port/raspberrypi/rp2xxx/src/hal/pwm.zig
This update the RP2xxx hal pwm.zig
- Fixes problem that prevented use of extra PWMs on RP2350B
- Added doc comments to most functions
- Fixed a name error in `set_channel_inversion`
=> Fixes to rp2xxx HAL pwm.zig 

port/raspberrypi/rp2xxx/src/hal.zig, port/raspberrypi/rp2xxx/src/hal/atomic.zig
This adds the missing RP2040 atomic external definitions to support Zig's `@atomicLoad`, `@atomicRmw`, `@aromicStore`, `@cmpxchgStrong` and `@cmpxchgWeak`. operations.
=> Rp2040 atomics

build-internals/build.zig, build.zig, core/src/cpus/cortex_m.zig, port/raspberrypi/rp2xxx/build.zig
This cleans up the hack I just added in #535.
This generalizes better, so it can be used for e.g. esp32c3 ram images.
=> Add ram_image boolean to mz.Target and expose via microzig.config

core/src/cpus/cortex_m.zig, port/raspberrypi/rp2xxx/rp2040.ld, port/raspberrypi/rp2xxx/rp2040_ram_image.ld
I changed this to `.isr_vector`, but I missed some targets. This restores it to the name used by the linker script generator.
=> Restore the microzig_flash_start section for ARM

port/raspberrypi/rp2xxx/src/cpus/hazard3.zig
The set_handler function tries to compare two unions, which zig does not permit.
Changed to compare one branch of the union.   Both branches are pointers so it does not matter which one we choose.
=> Fix bug in rp2350 hazard3's set_handler

examples/nordic/nrf5x/src/blinky.zig, examples/nordic/nrf5x/src/uart.zig, port/nordic/nrf5x/src/hal.zig, port/nordic/nrf5x/src/hal/time.zig, port/nordic/nrf5x/src/hal/uart.zig
TODO:
* Add interrupt handler for this timer that lets us keep time for more than 4 billion microseconds
* Call the initializer from some chip-specific file
=> nRF5x: Add basic timer support

examples/raspberrypi/rp2xxx/src/interrupts.zig, modules/riscv32-common/src/riscv32_common.zig, port/raspberrypi/rp2xxx/src/cpus/hazard3.zig
Fixes:
- riscv32_common.zig `is_pending` function need a compare to return a `bool`.
- hazard3.zig interrupt priority registers were incorrect.
- hazard3.zig removed an interrupt enable that tact1m4n3 didn't like.
=> Fixes to interrupt handling

port/espressif/esp/src/cpus/esp_riscv.zig
This makes the esp32 trap dispatch a bit more efficient.
The current version initially allocates a 160 byte stack frame (4*40) even though only 140 bytes (4*35) are used.   It then allocates an additional 16 bytes which are only used to preserve various values over function calls.
This change reduces the initial allocation to the required 140 bytes.  It eliminates the second 16 byte allocation entirely, using "s" registers to preserve values.  The "s" registers are themselves preserved by callconv(.c) functions.
=> esp32 Trap Dispatch Improvement

drivers/sensor/ICM-20948.zig, examples/nordic/nrf5x/src/i2c_accel.zig
I forgot to push a few changes to #591 before it was merged. Mostly just cleanup, but importantly it turns off `ACCEL_CYCLE`, which seems to need to be set to 0.
Before #591 I had a bug in how I set the bitfields for the LP_CONFIG register, which is why I suspect setting it to 1 was OK (it was actually setting another bit).
=> drivers: Cleanup ICM-20948 driver

port/raspberrypi/rp2xxx/src/hal/pio/assembler.zig, port/raspberrypi/rp2xxx/src/hal/pio/assembler/tokenizer.zig
std.memset.tokenize was deprecated in zig 0.14 https://ziglang.org/download/0.14.0/release-notes.html#List-of-Deprecations
The output when you get a PIO asm compile error still outputs a loot of whitespace before the error, but I'm not sure if something is wrong in the implementation or if this is intended:
```
/home/cortex/Projects/pixelmatrix/microzig/port/raspberrypi/rp2xxx/src/hal/pio/assembler.zig:129:13: error: failed to assemble PIO code:
out pins 6 side 0 [1]
^
.side_set directive must be specified for program to use side_set
@compileError(format_compile_error(d.message.slice(), source, d.index));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix deprecated tokenize->tokenizeAny in PIO assembler

tools/regz/src/Database.zig, tools/regz/src/patch.zig
Can be useful if you want to remove an enum from a field.
=> regz: optional enum in `set_enum_type` patch

core/src/cpus/cortex_m.zig, examples/raspberrypi/rp2xxx/src/i2c_bus_scan.zig, examples/raspberrypi/rp2xxx/src/mlx90640.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/hd44780.zig, examples/raspberrypi/rp2xxx/src/rp2040_only/pcf8574.zig, port/raspberrypi/rp2xxx/src/hal/dma.zig, port/raspberrypi/rp2xxx/src/hal/gpio.zig, port/raspberrypi/rp2xxx/src/hal/i2c.zig, port/raspberrypi/rp2xxx/src/hal/pio/assembler.zig, port/raspberrypi/rp2xxx/src/hal/pio/common.zig, port/raspberrypi/rp2xxx/src/hal/uart.zig
Extracted from #602 including nice commit history as well as no spurious debug changes
=> Several fixes and cleanups for RP2xxx

port/raspberrypi/rp2xxx/src/hal/gpio.zig, port/raspberrypi/rp2xxx/src/hal/pins.zig
Code:
```zig
const pin_config = rp2xxx.pins.GlobalConfiguration{
.GPIO29 = .{
.name = "relay",
.direction = .out,
},
.GPIO28 = .{
.name = "sensor",
.direction = .in,
},
.GPIO27 = .{
.name = "capacitor",
.direction = .in,
},
.GPIO4 = .{
.name = "SDA",
.function = .I2C0_SDA,
.schmitt_trigger = .enabled,
.slew_rate = .slow,
},
.GPIO5 = .{
.name = "SCL",
.function = .I2C0_SCL,
.schmitt_trigger = .enabled,
.slew_rate = .slow,
},
};
pub fn main() void {
pin_config.apply();
}
```
Causing:
```sh
install
└─ install generated to light-mcu.uf2
└─ run elf2uf2 (light-mcu.uf2)
└─ zig build-exe light-mcu ReleaseSmall thumb-freestanding-eabi 1 errors
/home/guney/.cache/zig/p/mz_port_raspberrypi_rp2xxx-0.0.0-wCvtidmzDQDWXpsuqBY_8dkz96PsJ_rrMKX04haxvjRt/src/hal/pins.zig:944:60: error: expected type …
```
=> rp2xxx: Remove SchmittTrigger, use  Enabled

drivers/sensor/ICM-20948.zig, examples/nordic/nrf5x/src/i2c_bus_scan.zig, examples/raspberrypi/rp2xxx/src/i2c_bus_scan.zig, tools/uf2/src/uf2.zig
* Fix error checks in bus scan (Read returns illegal address, not reserved)
* Rename `get_register` in the ICM-20948 driver to `get_reg` for consistency
* Remove redundant comptime size check: The size is verified because the packed struct has a size
=> Miscellaneous cleanup

tools/regz/src/svd.zig
nrf52 SVDs (at the very least) seem to use "writeonce" and "read-writeonce" rather than "writeOnce" and "read-writeOnce".
=> svd: Parse access type in case-insensitive manner

port/raspberrypi/rp2xxx/src/hal/pio/assembler.zig
Just a small oversight I ran into while trying to get a define by name from an assembled PIO program. Clearly, the comparison is supposed to be between the desired `name` and the current `define.name`, just as in `get_program_by_name`.
=> rp2xxx: fix incorrect parameter in define name comparison

core/src/utilities.zig
=> Fix incorrect calculation for get_readable_len in CircularBuffer

port/gigadevice/gd32/src/hals/GD32VF103/gpio.zig, port/raspberrypi/rp2xxx/src/hal/gpio.zig, port/raspberrypi/rp2xxx/src/hal/pwm.zig, port/stmicro/stm32/src/hals/STM32F103/gpio.zig
- Removed some leftover debug logging in PWM that was spamming progra…m logs
- Removed unused scoped loggers from other parts of the HAL
Found this today when I used PWM on the Pico and all of the sudden my log window got flooded :)
=> Remove Leftover Debug Logging

examples/nordic/nrf5x/build.zig, examples/nordic/nrf5x/src/rtt_log.zig, modules/rtt/README.md
Wanted to try out RTT, and I already had my nrf52 connected to the debugger. Confirmed it worked, so figured I'd add an example.
Copied almost exactly from the rp2xxx example.
```
$ pyocd rtt
...
0000355 I 1 up channels and 1 down channels found [rtt_cmd]
0000355 I Reading from up channel 0 ("Terminal") [rtt_cmd]
0000356 I Writing to down channel 0 ("Terminal") [rtt_cmd]
Hello RTT!
[2.000030] info: Hello!
[4.000000] info: Hello!
[6.000000] info: Hello!
[8.000000] info: Hello!
[10.000000] info: Hello!
h[10.476501] info: Got a line: "h"
e[10.911987] info: Got a line: "e"
l[11.229705] info: Got a line: "l"
l[11.391265] info: Got a line: "l"
o[11.476043] info: Got a line: "o"
```
=> nrf52: Add rtt example

examples/stmicro/stm32/src/stm32f1xx/adc.zig, examples/stmicro/stm32/src/stm32f1xx/adc_dualmode.zig, examples/stmicro/stm32/src/stm32f1xx/advanced_adc.zig, examples/stmicro/stm32/src/stm32f1xx/gpio.zig, examples/stmicro/stm32/src/stm32f1xx/hd44780.zig, examples/stmicro/stm32/src/stm32f1xx/i2c.zig, examples/stmicro/stm32/src/stm32f1xx/i2c_bus_scan.zig, examples/stmicro/stm32/src/stm32f1xx/spi.zig, examples/stmicro/stm32/src/stm32f1xx/ssd1306.zig, examples/stmicro/stm32/src/stm32f1xx/timer.zig, examples/stmicro/stm32/src/stm32f1xx/timer_capture.zig, examples/stmicro/stm32/src/stm32f1xx/uart_echo.zig, examples/stmicro/stm32/src/stm32f1xx/usb_cdc.zig, examples/stmicro/stm32/src/stm32f1xx/usb_hid.zig, port/stmicro/stm32/src/hals/STM32F103/adc.zig, port/stmicro/stm32/src/hals/STM32F103/drivers.zig, port/stmicro/stm32/src/hals/STM32F103/hal.zig, port/stmicro/stm32/src/hals/STM32F103/i2c.zig, port/stmicro/stm32/src/hals/STM32F103/rcc.zig, port/stmicro/stm32/src/hals/STM32F103/rtc.zig, port/stmicro/stm32/src/hals/STM32F103/time.zig, port/stmicro/stm32/src/hals/STM32F103/timer.zig, port/stmicro/stm32/src/hals/STM32F103/uart.zig, port/stmicro/stm32/src/hals/STM32F103/usb_internals/usb_ll.zig, port/stmicro/stm32/src/hals/STM32F103/util.zig
RTC and GP-Timer time driver for the STM32F1xx
Bug fix: 
- HSE/128 is now configured correctly.
=> STM32F1 Time Driver

core/src/core/usb/cdc.zig
Line state can be useful when waiting for a terminal to connect before trying to write/read.  This adds a line state variable to track that.
=> Update cdc.zig with line state tracking

port/raspberrypi/rp2xxx/src/hal/usb.zig
See also "4.1.2.7.1. Concurrent access" in the RP2040 datasheet.
=> Ensure RP2040 tx buffer control is respected
