ZigEmbeddedGroup/microzig

build.zig
src/main.zig
src/modules/Board.zig
src/modules/Chip.zig
src/modules/Cpu.zig
src/modules/LinkerScriptStep.zig
src/modules/boards.zig
src/modules/chips.zig
src/modules/chips/stm32f103/registers.zig
src/modules/chips/stm32f103/stm32f103.zig
src/modules/cpus.zig
tests/blinky.zig

add stm32f103 registers and reorganize

---

src/core/start.zig

As discussed earlier today in Discord \#microzig.

After #23 repair Reset on stm32, lpc1768

---

build.zig
src/modules/boards/mbed-lpc1768/mbed-lpc1768.zig
src/modules/chips/lpc1768/lpc1768.zig
src/modules/chips/stm32f407/stm32f407.zig
tests/uart-sync.zig

Also fix some minor issues on lpc1768

Add Uart to STM32F4Discovery and rework uart-sync example

---

src/modules/chips.zig

Well it took me a week and a ton of help from zig embedded people on discord, especially @mattnite (thanks!), but now blink is working on my bluepill!

changing linker memory locations for stm32f103c8

---

build.zig
src/main.zig

improve build api

---

src/modules/cpus.zig
src/modules/cpus/cortex-m/cortex-m.zig

Fixes: [64](https://github.com/ZigEmbeddedGroup/microzig/issues/64)

Allow to specify VectorTable in app and hal.

---

src/main.zig

Reverts ZigEmbeddedGroup/microzig#79

Revert "Add executable methods and fix recursive call"

---

src/main.zig

Reverts ZigEmbeddedGroup/microzig#81
now we're talking

Revert "Revert "Add executable methods and fix recursive call""

---

.github/workflows/auto-pr.yml

Automerge action step doesn't work with this setup so we'll have to manually merge

Add rest of hardware support libraries

---

README.adoc
src/core/experimental/gpio.zig
src/core/experimental/pin.zig

I have also updated the readme build example as that has changed as well.

Updated parts of gpio and pin to reflect code changes from regz rewrite

---

README.adoc

direct new users to microzig-examples for ease
the onboarding experience.

doc: add getting started tip

---

bsp/microchip/avr/build.zig
bsp/microchip/avr/src/boards/itsybitsy_32u4.zig
bsp/microchip/avr/src/chips/ATmega32U4.json
bsp/microchip/avr/src/hals/ATmega32U4.zig

Basic support for ATmega32u4

---

build.zig
core/src/cpus/avr5.zig
core/src/start.zig

fix(avr5): fix building blinking examples

---

README.md

I notice that following the instructions didn't quite work without a few missing details.
some of the dissusion is here:
https://discord.com/channels/824493524413710336/1287522497545371688

Update some of the getting started details.

---

core/build.zig
core/src/microzig.zig
core/src/utilities.zig
port/raspberrypi/rp2xxx/src/hal/i2c.zig
port/raspberrypi/rp2xxx/src/hal/spi.zig
port/raspberrypi/rp2xxx/src/hal/time.zig
port/raspberrypi/rp2xxx/src/hal/uart.zig

I've started implementing the writev/readv parts of the code and did some chores to clean up the code on the go
Not mergable yet as SPI devices are missing. Will add them and do some more cleanups before we're ready to merge

RP2 writev/readv implementation

---

port/raspberrypi/rp2xxx/src/hal/pio.zig

When configuring PINs for use with PIO SMs, currently we only set the pin bases and counts for each group of pins inside the `PINCTRL` register. This does not affect the actual direction and default value that these pins will have from the point-of-view of the state machine.
The pico-sdk will [internally configure the desired pins](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2_common/hardware_pio/pio.c#L234-L268). It does that by saving the `PINCTRL` and `EXECTRL` registers, then it configures the `SET` group to the pin we want to configure so that it can execute `SET PINDIRS, n` or `SET PINS, n` for the pin(s) being configured.
Eventually it would be ideal to include pin value and pin direction configuration as part of the …

Add helpers for reading from PIO RX FIFO and for PIO SM pin configuration

---

core/src/core/usb.zig
core/src/core/usb/cdc.zig
core/src/core/usb/hid.zig
core/src/core/usb/types.zig
examples/raspberrypi/rp2xxx/src/rp2040_only/usb_cdc.zig
port/raspberrypi/rp2xxx/src/hal/usb.zig

This PR does two things:
1. Improves CDC serial writing interface. Now string of arbitrary size can be write/send to host so previous hack and very basis example is removed and replaced with much better one.
2. CDC read interface is introduced. Although it not always works (there is special comment in code that points all related issues). I hope somone will be able to help me with that.

USB CDC - improve writing and implement reading (almost)

---

core/src/core/usb.zig
core/src/core/usb/types.zig
port/raspberrypi/rp2xxx/src/hal/usb.zig

My previous commit #293 improved CDC reading and introduced writig interface but as I mentioned there - reading was sometimes working and sometimes not. This PR is fixing that so reading should finally work as expected.

Fix USB CDC receive code

---

examples/wch/ch32v/src/empty.zig
port/wch/ch32v/README.md
port/wch/ch32v/build.zig
port/wch/ch32v/src/chips/ch32v003.svd
port/wch/ch32v/src/chips/ch32v103.svd
port/wch/ch32v/src/chips/ch32v20x.svd
port/wch/ch32v/src/cpus/qingkev2-rv32ec.zig
port/wch/ch32v/src/cpus/qingkev3-rv32imac.zig
port/wch/ch32v/src/cpus/qingkev4-rv32imac.zig
port/wch/ch32v/src/hals/hal_ch32v003.zig
port/wch/ch32v/test/programs/minimal.zig
tools/regz/src/Database.zig
tools/regz/src/arch/riscv.zig
tools/regz/src/gen.zig
tools/regz/src/svd.zig

This Pull Request is an update of PR #223 by @akiroz to be mergiable to the current HEAD.
His/her work is targeted for CH32V003 and I have extended that for other WCH's CH32V series CPUs, CH32V103 and CH32V203. 
I have confirmed this PR works on my CH32V targets.

Updated PR #223 for current HEAD and extended it for other WCH's CH32V series.

---

port/raspberrypi/rp2xxx/src/hal/irq.zig

- Reworked the IRQ API to be a little easier to use + made it actually work :)

Fix NVIC level IRQ control for RP2040

---

examples/raspberrypi/rp2xxx/build.zig
examples/raspberrypi/rp2xxx/src/rp2040_only/rtc.zig
port/raspberrypi/rp2xxx/src/hal.zig
port/raspberrypi/rp2xxx/src/hal/clocks/rp2040.zig
port/raspberrypi/rp2xxx/src/hal/rtc.zig

Used the RTC in a personal project so decided to upstream support into MicroZig!
- Added support for RTC to RP2040
- Added an example showing the RTC generating an interrupt every minute
- RP2350 doesn't have an "RTC" module, so nothing to add there

RTC Support for RP2040

---

port/stmicro/stm32/src/generate.zig

This commit adds support for items with multiple start-end points inside of the bit_offset field of the json data. (its for the STM32).

Supporting non-contiguous registers

---

core/src/core/experimental.zig
core/src/core/experimental/semihosting.zig
examples/stmicro/stm32/build.zig
examples/stmicro/stm32/src/semihosting.zig

This is just a test, I'm still porting semihosting
I will document the updates in this PR

Add basic support to semihosting

---

examples/raspberrypi/rp2xxx/src/interrupts.zig

I was confused how a toggle with 0 worked, since it should just keep the value the same.
Turns out that this register is 'write-to-clear' so toggle with 0 just rewrites the same value back, which happens to work.
This PR simply clarifies what's happening by using `modify`

examples: rp2xxx: interrupts: Cleanup and clarify cleaning behaviour

---

website/layouts/templates/base.shtml

add build date to website

---

port/raspberrypi/rp2xxx/src/hal.zig
port/raspberrypi/rp2xxx/src/hal/multicore.zig

I wrote this to allow managing spinlocks with the lock-defer-unlock pattern.
Also added code to clear spinlocks on soft reset as the RP2040 doesn't do that automatically.

Spin lock management

---

core/src/core/usb/hid.zig

- Add new usage constants to support keyboard report descriptor
- Add usage min/max helpers to support keyboard report descriptor
- Add report descriptor for a keyboard report conforming to the boot protocol
Reference: https://usb.org/sites/default/files/hid1_11.pdf appendix B.1

HID: report descriptor for boot keyboard

---

drivers/build.zig.zon
drivers/framework.zig
drivers/sensor/TMP117.zig

Add a TMP116/117 temperature sensor driver.
Sample code I use to test it:
```zig
const std = @import("std");
const microzig = @import("microzig");
const rp2xxx = microzig.hal;
const i2c = rp2xxx.i2c;
const gpio = rp2xxx.gpio;
const peripherals = microzig.chip.peripherals;
const time = rp2xxx.time;
pub const microzig_options = microzig.Options{
.log_level = .info,
.logFn = rp2xxx.uart.logFn,
};
const uart = rp2xxx.uart.instance.num(0);
const baud_rate = 115200;
const uart_tx_pin = gpio.num(0);
const i2c0 = i2c.instance.num(1);
pub fn main() !void {
uart_tx_pin.set_function(.uart);
uart.apply(.{ .baud_rate = baud_rate, .clock_config = rp2xxx.clock_config });
rp2xxx.uart.init_logger(uart);
const scl_pin = gpio.num(27);
const sda_pin = gpio.num(26);
inline for (&.{ scl_pin, sda_pin }) |pin| { …
```

Drivers: Add TMP117 temperature driver

---

core/src/core/usb/cdc.zig
core/src/core/usb/hid.zig
core/src/core/usb/templates.zig
core/src/core/usb/types.zig
core/src/core/usb/utils.zig
core/src/core/usb/vendor.zig

Format code related to USB. The changes are just whitespace and trailing commas.
I decided not to fmt the whole repo right now because it's a lot to review at once.

usb: zig fmt

---

core/src/concurrency.zig
core/src/microzig.zig
port/raspberrypi/rp2xxx/src/hal.zig
port/raspberrypi/rp2xxx/src/hal/atomic.zig
port/raspberrypi/rp2xxx/src/hal/dma.zig
port/raspberrypi/rp2xxx/src/hal/multicore.zig
port/raspberrypi/rp2xxx/src/hal/mutex.zig

- Introduce `AtomicStaticBitSet`
- Atomics support for RP2040
- Make DMA use `AtomicStaticBitSet`

Atomics support for RP2040

---

drivers/io_expander/pcf8574.zig

add @alignCast PCF8574 driver

---

core/src/microzig.zig
port/espressif/esp/esp32_c3.ld
port/raspberrypi/rp2xxx/src/hal.zig
port/raspberrypi/rp2xxx/src/hal/image_def.zig

- add `HAL_Options`
- configure `image_def` security using `HAL_Options`

Introduce `HAL_Options`

---

drivers/base/Datagram_Device.zig

Add support to the test device for #574

Add writev_then_readv to the test Datagram_Device

---

drivers/base/Clock_Device.zig

Also update the test device to crucially provide this (as a no-op) so that we can sleep call driver methods that sleep in tests without hanging.

Clock_Device: Allow providing sleep function to avoid polling

---

port/raspberrypi/rp2xxx/src/hal/pio/assembler/encoder.zig

This PR fixes an overflow when a PIO program contains exactly 32 instructions (the maximum number).

RP2xxx: Fix overflow when PIO programs contain 32 instructions

---

port/raspberrypi/rp2xxx/src/hal/multicore.zig

This can be useful in multithreaded code (I needed this in my project).

RP2xxx: Add try_lock to spinlocks.

---

port/wch/ch32v/build.zig

CH32F003 - Flash to start 0x0

---

examples/espressif/esp/README.md
examples/espressif/esp/build.zig
examples/espressif/esp/src/custom_clock_config.zig
examples/espressif/esp/src/systimer.zig
examples/espressif/esp/src/ws2812_blinky.zig
port/espressif/esp/build.zig
port/espressif/esp/ld/esp32_c3/flashless_sections.ld

- add flashless target
- remove log_level from some examples for consistency

esp: ESP32-C3 flashless target

---

port/raspberrypi/rp2xxx/src/hal.zig
port/raspberrypi/rp2xxx/src/hal/flash.zig
port/raspberrypi/rp2xxx/src/hal/rom.zig
port/raspberrypi/rp2xxx/src/hal/rom/rp2040.zig
port/raspberrypi/rp2xxx/src/hal/rom/rp2350.zig

For the future:
- export rom optimized math functions for rp2040

rp2xxx: rom refactoring and support for rp2350

---

examples/espressif/esp/build.zig
examples/espressif/esp/src/blinky.zig
examples/espressif/esp/src/gpio_input.zig
examples/espressif/esp/src/i2c_bus_scan.zig
examples/espressif/esp/src/i2c_display_sh1106.zig
examples/espressif/esp/src/i2c_temp.zig
examples/espressif/esp/src/ledc_pwm_servo.zig
examples/espressif/esp/src/ws2812_blinky.zig
port/espressif/esp/src/hal.zig
port/espressif/esp/src/hal/cache.zig
port/espressif/esp/src/hal/clocks.zig
port/espressif/esp/src/hal/clocks/esp32_c3.zig
port/espressif/esp/src/hal/drivers.zig
port/espressif/esp/src/hal/efuse.zig
port/espressif/esp/src/hal/gpio.zig
port/espressif/esp/src/hal/i2c.zig
port/espressif/esp/src/hal/ledc.zig
port/espressif/esp/src/hal/rom.zig
port/espressif/esp/src/hal/spi.zig
port/espressif/esp/src/hal/systimer.zig
port/espressif/esp/src/hal/time.zig

* Add LEDC hal and examples
* Refactor GPIO hal
* Refactor SPI hal (in the spirit of the others)
* Unified way to connect pins to peripherals

esp: LEDC and refactoring
